from .collections.dict import (
    dict_not_empty,
    dict_length,
    dict_min_length,
    dict_max_length,
)
from .collections.list import (
    list_not_empty,
    list_unique,
    list_unique_not_empty,
    list_of,
    list_length,
    list_min_length,
    list_max_length,
)
from .collections.set import (
    set_not_empty,
    set_of,
    set_length,
    set_min_length,
    set_max_length,
)
from .collections.tuple import (
    tuple_not_empty,
    tuple_of,
    tuple_length,
    tuple_min_length,
    tuple_max_length,
)
from .primitives.bool import (
    bool_true,
    bool_false,
)
from .primitives.bytes import (
    bytes_empty,
    bytes_not_empty,
    bytes_length,
    bytes_min_length,
    bytes_max_length,
    bytes_length_range,
)
from .primitives.float import (
    float_positive,
    float_negative,
    float_non_negative,
    float_non_positive,
    float_zero,
    float_not_zero,
    float_finite,
    float_not_nan,
    float_not_infinite,
    float_probability,
    float_percentage,
    float_latitude,
    float_longitude,
    float_gt,
    float_ge,
    float_lt,
    float_le,
    float_in_range,
)
from .primitives.int import (
    int_positive,
    int_negative,
    int_non_negative,
    int_non_positive,
    int_zero,
    int_not_zero,
    int_even,
    int_odd,
    int_positive_even,
    int_positive_odd,
    int_non_negative_even,
    int_uint8,
    int_int8,
    int_percentage,
    int_port,
    int_year,
    int_month,
    int_day_of_month,
    int_hour,
    int_minute,
    int_second,
    int_gt,
    int_ge,
    int_lt,
    int_le,
    int_eq,
    int_ne,
    int_in_range,
    int_divisible_by,
    int_multiple_of,
)
from .primitives.int_float import (
    int_float_positive,
    int_float_negative,
    int_float_non_negative,
    int_float_non_positive,
    int_float_zero,
    int_float_not_zero,
    int_float_finite,
    int_float_in_range,
)
from .primitives.str import (
    str_empty,
    str_not_empty,
    str_blank,
    str_not_blank,
    str_whitespace,
    str_alpha,
    str_alnum,
    str_digit,
    str_ascii,
    str_printable,
    str_lower,
    str_upper,
    str_title,
    str_no_whitespace,
    str_single_line,
    str_identifier,
    str_slug,
    str_snake_case,
    str_email,
    str_url,
    str_uuid,
    str_hex_color,
    str_length,
    str_min_length,
    str_max_length,
    str_length_range,
    str_starts_with,
    str_ends_with,
    str_contains,
    str_matches,
    str_one_of,
)


__all__ = [
    # collections/dict
    "dict_not_empty",
    "dict_length",
    "dict_min_length",
    "dict_max_length",
    # collections/list
    "list_not_empty",
    "list_unique",
    "list_unique_not_empty",
    "list_of",
    "list_length",
    "list_min_length",
    "list_max_length",
    # collections/set
    "set_not_empty",
    "set_of",
    "set_length",
    "set_min_length",
    "set_max_length",
    # collections/tuple
    "tuple_not_empty",
    "tuple_of",
    "tuple_length",
    "tuple_min_length",
    "tuple_max_length",
    # types/bool
    "bool_true",
    "bool_false",
    # types/bytes
    "bytes_empty",
    "bytes_not_empty",
    "bytes_length",
    "bytes_min_length",
    "bytes_max_length",
    "bytes_length_range",
    # types/float
    "float_positive",
    "float_negative",
    "float_non_negative",
    "float_non_positive",
    "float_zero",
    "float_not_zero",
    "float_finite",
    "float_not_nan",
    "float_not_infinite",
    "float_probability",
    "float_percentage",
    "float_latitude",
    "float_longitude",
    "float_gt",
    "float_ge",
    "float_lt",
    "float_le",
    "float_in_range",
    # types/int
    "int_positive",
    "int_negative",
    "int_non_negative",
    "int_non_positive",
    "int_zero",
    "int_not_zero",
    "int_even",
    "int_odd",
    "int_positive_even",
    "int_positive_odd",
    "int_non_negative_even",
    "int_uint8",
    "int_int8",
    "int_percentage",
    "int_port",
    "int_year",
    "int_month",
    "int_day_of_month",
    "int_hour",
    "int_minute",
    "int_second",
    "int_gt",
    "int_ge",
    "int_lt",
    "int_le",
    "int_eq",
    "int_ne",
    "int_in_range",
    "int_divisible_by",
    "int_multiple_of",
    # types/int_float
    "int_float_positive",
    "int_float_negative",
    "int_float_non_negative",
    "int_float_non_positive",
    "int_float_zero",
    "int_float_not_zero",
    "int_float_finite",
    "int_float_in_range",
    # types/str
    "str_empty",
    "str_not_empty",
    "str_blank",
    "str_not_blank",
    "str_whitespace",
    "str_alpha",
    "str_alnum",
    "str_digit",
    "str_ascii",
    "str_printable",
    "str_lower",
    "str_upper",
    "str_title",
    "str_no_whitespace",
    "str_single_line",
    "str_identifier",
    "str_slug",
    "str_snake_case",
    "str_email",
    "str_url",
    "str_uuid",
    "str_hex_color",
    "str_length",
    "str_min_length",
    "str_max_length",
    "str_length_range",
    "str_starts_with",
    "str_ends_with",
    "str_contains",
    "str_matches",
    "str_one_of",
]


_DESIGN_NOTES = """
# simplibs-types — Package Overview

## Purpose
The top-level entry point of `simplibs-types`. Re-exports ready-made
preset type from `presets/colections` and `presets/types`, so a caller
never has to reach into the internal folder structure directly:

    from simplibs.types import int_positive, str_email, validated_type

## Internal Components Registry

| Component            | Type      | Description                                                     |
| :---------------------- | :-------- | :-------------------------------------------------------------------- |
| `presets.colections.*`   | Sub-Package | Container presets (`dict`, `list`, `set`, `tuple`).                   |
| `presets.types.*`        | Sub-Package | Scalar type presets (`bool`, `bytes`, `float`, `int`, `number`, `str`).|
"""